[package]
name = "mostro"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Francisco Calderón <fjcalderon@gmail.com>"]
description = "Lightning Network peer-to-peer nostr platform"

[dependencies]
anyhow = "1.0.66"
env = "0.0.0"
log = "0.4.17"
nostr = "0.5.1"
nostr-sdk = "0.5.1"
serde = { version = "1.0.149" }
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["full"] }
